import { SalaryRecord } from './types';

export const mockRecords: SalaryRecord[] = [
  {
    id: '1',
    employee: 'Thomas Miller',
    role: 'General Manager',
    department: 'Management',
    prevSalary: '$90,000',
    newSalary: '$95,000',
    incrementAmount: '+$5,000',
    incrementPercent: '+5.56%',
    monthlyIncrease: '+$417/mo',
    effectiveDate: '2026-01-01',
    nextReviewDate: '2027-01-01',
    reason: 'Annual performance review',
    approvedBy: 'CEO',
    status: 'Active',
  },
  {
    id: '2',
    employee: 'Sarah Chen',
    role: 'Head Housekeeper',
    department: 'Housekeeping',
    prevSalary: '$50,000',
    newSalary: '$52,000',
    incrementAmount: '+$2,000',
    incrementPercent: '+4%',
    monthlyIncrease: '+$167/mo',
    effectiveDate: '2026-01-01',
    nextReviewDate: '2027-01-01',
    reason: 'Cost of living adjustment',
    approvedBy: 'HR Director',
    status: 'HR Approved',
  },
  {
    id: '3',
    employee: 'Robert Davis',
    role: 'Security Manager',
    department: 'Security',
    prevSalary: '$52,000',
    newSalary: '$54,000',
    incrementAmount: '+$2,000',
    incrementPercent: '+3.85%',
    monthlyIncrease: '+$167/mo',
    effectiveDate: '2026-06-01',
    nextReviewDate: '2027-06-01',
    reason: 'Annual cost-of-living adjustment',
    approvedBy: 'Pending approval',
    status: 'Pending',
  },
  {
    id: '4',
    employee: 'David Rodriguez',
    role: 'Chef de Cuisine',
    department: 'Kitchen',
    prevSalary: '$64,000',
    newSalary: '$68,000',
    incrementAmount: '+$4,000',
    incrementPercent: '+6.25%',
    monthlyIncrease: '+$333/mo',
    effectiveDate: '2026-04-01',
    nextReviewDate: '2027-04-01',
    reason: 'Skills increment — Michelin recognition training',
    approvedBy: 'Jennifer Thomas',
    status: 'Active',
  },
];
