export const routes = {
  dashboard: '/dashboard',
  reservations: '/reservations',
  roomPlan: '/room-plan',
  guests: '/guests',
  reports: '/reports',
  complaints: '/complaints',
  housekeeping: '/housekeeping',
  servicesRequests: '/services-requests',
  inHouseList: '/in-house-list',
  roomAllocation: '/room-allocation',
  roomAllocationGroup: '/room-allocation/group',
  roomAllocationDetails: '/room-allocation/:id',
  salesRevenue: {
    dashboard: '/sales-revenue',
    rateCalendar: '/sales-revenue/rate-calendar',
    roomTypes: '/sales-revenue/room-types',
    pricing: '/sales-revenue/pricing',
    corporateAccount: '/sales-revenue/corporate-account',
    groupContracts: '/sales-revenue/group-contracts',
    productionReport: '/sales-revenue/production-report',
    discounts: '/sales-revenue/discounts',
    packages: '/sales-revenue/packages',
  },
  laundry: {
    overview: '/laundry/overview',
    roomRequests: '/laundry/room-requests',
    inventory: '/laundry/inventory',
    settings: '/laundry/settings',
  },
  hk: {
    dashboard: '/HK/Dashboard',
    cleaningTasks: '/HK/CleaningTasks',
    guestRequests: '/HK/GuestRequests',
    foundsAndLost: '/HK/FoundsAndLost',
    inventory: '/HK/Inventory',
    settings: '/HK/Settings',
  },
  hrm: {
    dashboard: '/HRM/Dashboard',
    employees: '/HRM/Employees',
    shiftManagement: '/HRM/ShiftManagement',
    attendance: '/HRM/Attendance',
    leaveManagement: '/HRM/LeaveManagement',
    departments: '/HRM/Departments',
    salaryIncrements: '/HRM/SalaryIncrements',
    payroll: '/HRM/Payroll',
    setting: {
      root: '/HRM/Setting',
      departments: '/HRM/Setting/Departments',
      shifts: '/HRM/Setting/Shifts',
      notifications: '/HRM/Setting/Notifications',
      positions: '/HRM/Setting/Positions',
    },
  },
  login: '/login',
} as const

export type RoutePath = (typeof routes)[keyof typeof routes]
